### ISSUE TITLE
`ruff format` / `ruff` sequence

### ISSUE THREAD

**Issue by DimitriPapadopoulos** [pypa/pipx#1404]
**Describe the bug**

As far as I know, the proper sequence is running `ruff ` followed by `ruff format`. From [ruff-pre-commit](https://github.com/astral-sh/ruff-pre-commit):
> When running with `--fix`, Ruff's lint hook should be placed _before_ Ruff's formatter hook, and _before_ Black, isort, and other formatting tools, as Ruff's fix behavior can output code changes that require reformatting.
> 
> When running without `--fix`, Ruff's formatter hook can be placed before or after Ruff's lint hook.
> 
> (As long as your Ruff configuration avoids any [linter-formatter incompatibilities](https://docs.astral.sh/ruff/formatter/#conflicting-lint-rules), `ruff format` should never introduce new lint errors, so it's safe to run Ruff's format hook after `ruff check --fix.`)

**How to reproduce**

https://github.com/pypa/pipx/blob/964d93c948a8e1faf134e3de148e5f4faf220ad6/.pre-commit-config.yaml#L13-L18

**Expected behavior**

```yaml
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.4.3
  hooks:
  - id: ruff
    args: [ "--fix", "--unsafe-fixes", "--exit-non-zero-on-fix"]
  - id: ruff-format
```
