### ISSUE TITLE
How to install a package with specific dependencies

### ISSUE THREAD

**Issue by chriscroome** [pypa/pipx#936]
In the past I've been able to install [JMESPath Terminal](https://github.com/jmespath/jmespath.terminal) using Ansible and PIP, for example:

```yaml
---
- name: JMESPath Terminal present
  block:

    # https://github.com/jmespath/jmespath.terminal/issues/19#issuecomment-1156039074
    - name: Use pip to install an old version of setuptools
      ansible.builtin.pip:
        name: setuptools==57
        state: present

    - name: Use pip to install jpterm
      ansible.builtin.pip:
        name: jmespath-terminal
        state: present

  when: jp_term | bool
```

However Debian Bookworm is not going to allow this:

> python-pip (23.0+dfsg-1) unstable; urgency=medium
>
> This version of pip introduces PEP 668 support. Debian's python3.11 interpreter will soon (>= 3.11.1-3) declare the installation to be EXTERNALLY-MANAGED, instructing pip to disallow package installation outside virtualenvs.
>
> See: https://peps.python.org/pep-0668/
>
> Practically, this means that you can't use pip to install packages outside a virtualenv, on a Debian system, any more.

So I'm looking to update everything to use `pipx`, however I can't see how to install `setuptools==57` and then `jmespath-terminal` into a `venv`, is this possible?
